/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Juan Figueroa
 */
public class Form_Menu extends javax.swing.JFrame {

    /**
     * Creates new form FormMen
     */
    public Form_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtn_recetas = new javax.swing.JButton();
        jbtn_cocteles = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jbtm_ensaladas = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jbtn_agregar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(2147483, 2147483));
        setMinimumSize(getMaximumSize());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtn_recetas.setForeground(new java.awt.Color(238, 238, 238));
        jbtn_recetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/boton_recetas.png"))); // NOI18N
        jbtn_recetas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jbtn_recetas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn_recetas.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/boton_recetas_press.png"))); // NOI18N
        jbtn_recetas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/boton_recetas_over.png"))); // NOI18N
        jbtn_recetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_recetasActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_recetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 410, 250));

        jbtn_cocteles.setForeground(new java.awt.Color(238, 238, 238));
        jbtn_cocteles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/boton_coctel.png"))); // NOI18N
        jbtn_cocteles.setBorder(null);
        jbtn_cocteles.setBorderPainted(false);
        jbtn_cocteles.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn_cocteles.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/boton_coctel_press.png"))); // NOI18N
        jbtn_cocteles.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/boton_coctel_over.png"))); // NOI18N
        getContentPane().add(jbtn_cocteles, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 550, 410, 250));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/titulo_v2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 670, 240));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/boton_postre.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/boton_postre_press.png"))); // NOI18N
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/boton_postre_over.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 550, 410, 250));

        jbtm_ensaladas.setForeground(new java.awt.Color(238, 238, 238));
        jbtm_ensaladas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/boton_ensaladas.png"))); // NOI18N
        jbtm_ensaladas.setBorder(null);
        jbtm_ensaladas.setBorderPainted(false);
        jbtm_ensaladas.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/boton_ensaladas_press.png"))); // NOI18N
        jbtm_ensaladas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/boton_ensaladas_over.png"))); // NOI18N
        getContentPane().add(jbtm_ensaladas, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 260, 410, 250));

        jButton1.setText("jButton1");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 350, -1, -1));

        jMenu1.setText("File");

        jbtn_agregar.setText("Agregar Receta");
        jMenu1.add(jbtn_agregar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");

        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_recetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_recetasActionPerformed
        FormListaReceta receta = new FormListaReceta();
        receta.setVisible(true);
        //dispose();
    }//GEN-LAST:event_jbtn_recetasActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JButton jbtm_ensaladas;
    private javax.swing.JMenuItem jbtn_agregar;
    private javax.swing.JButton jbtn_cocteles;
    private javax.swing.JButton jbtn_recetas;
    // End of variables declaration//GEN-END:variables
}
