
package Vista;

/**
 *
 * @author Juan Figueroa
 * @version 13-11-2022
 */
public class FormMenu extends javax.swing.JPanel {

    /**
     * Creates new form FormMenu
     */
    public FormMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbtn_listaReceta = new javax.swing.JButton();
        jbtn_listaCoctel = new javax.swing.JButton();
        jbtn_nuevaReceta = new javax.swing.JButton();
        jbtn_nuevoCoctel = new javax.swing.JButton();
        jbtn_cambiarReceta = new javax.swing.JButton();
        jbtn_cambiarCoctel = new javax.swing.JButton();
        jbtn_salir = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Menu de Recetas");

        jbtn_listaReceta.setText("Lista de Recetas");
        jbtn_listaReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_listaRecetaActionPerformed(evt);
            }
        });

        jbtn_listaCoctel.setText("Lista de Cóctel");
        jbtn_listaCoctel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_listaCoctelActionPerformed(evt);
            }
        });

        jbtn_nuevaReceta.setText("Nueva Receta");
        jbtn_nuevaReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_nuevaRecetaActionPerformed(evt);
            }
        });

        jbtn_nuevoCoctel.setText("Nuevo Cóctel");
        jbtn_nuevoCoctel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_nuevoCoctelActionPerformed(evt);
            }
        });

        jbtn_cambiarReceta.setText("Cambiar Receta");
        jbtn_cambiarReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_cambiarRecetaActionPerformed(evt);
            }
        });

        jbtn_cambiarCoctel.setText("Cambiar Cóctel");

        jButton7.setText("Salir");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtn_listaReceta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_nuevaReceta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_cambiarReceta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtn_listaCoctel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_nuevoCoctel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_cambiarCoctel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jbtn_salir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_listaReceta)
                    .addComponent(jbtn_listaCoctel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_nuevaReceta)
                    .addComponent(jbtn_nuevoCoctel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_cambiarReceta)
                    .addComponent(jbtn_cambiarCoctel))
                .addGap(18, 18, 18)
                .addComponent(jbtn_salir)
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void jbtn_listaRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_listaRecetaActionPerformed
        
        FormListaReceta flr = new FormListaReceta();
        flr.setVisible(true);
        
    }//GEN-LAST:event_jbtn_listaRecetaActionPerformed

    private void jbtn_listaCoctelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_listaCoctelActionPerformed
        
        FormListaCoctel flc = new FormListaCoctel();
        flc.setVisible(true);
        
    }//GEN-LAST:event_jbtn_listaCoctelActionPerformed

    private void jbtn_nuevaRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_nuevaRecetaActionPerformed
        
        FormNuevaReceta fnr = new FormNuevaReceta();
        fnr.setVisible(true);
        
    }//GEN-LAST:event_jbtn_nuevaRecetaActionPerformed

    private void jbtn_nuevoCoctelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_nuevoCoctelActionPerformed
        
        FormNuevoCoctel fnc = new FormNuevoCoctel();
        fnc.setVisible(true);
        
    }//GEN-LAST:event_jbtn_nuevoCoctelActionPerformed

    private void jbtn_cambiarRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_cambiarRecetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_cambiarRecetaActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtn_cambiarCoctel;
    private javax.swing.JButton jbtn_cambiarReceta;
    private javax.swing.JButton jbtn_listaCoctel;
    private javax.swing.JButton jbtn_listaReceta;
    private javax.swing.JButton jbtn_nuevaReceta;
    private javax.swing.JButton jbtn_nuevoCoctel;
    private javax.swing.JButton jbtn_salir;
    // End of variables declaration//GEN-END:variables
}
