/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Bd.Conexion;
import Controlador.RegistroUsuario;
import Modelo.Usuario;
import java.sql.Connection;
import javax.swing.JOptionPane;


/**
 *
 * @author MONKEY.D.LUFFY
 */
public class Form_Registro extends javax.swing.JFrame {

    /**
     * Creates new form FormRegistro
     */
    public Form_Registro() {
        initComponents();
        
        this.jlbl_email.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_nombre = new javax.swing.JLabel();
        jtxt_nombreUsuario = new javax.swing.JTextField();
        jLabel_correo = new javax.swing.JLabel();
        jtxt_correo = new javax.swing.JTextField();
        jLabel_contraseña = new javax.swing.JLabel();
        jbtn_cancelar = new javax.swing.JButton();
        jbtn_guardar = new javax.swing.JButton();
        jpass_contraseña = new javax.swing.JPasswordField();
        jlbl_email = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jpass_repeatContraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRO DE USUARIO");

        jLabel_nombre.setText("Nombre de usuario:");

        jtxt_nombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_nombreUsuarioActionPerformed(evt);
            }
        });

        jLabel_correo.setText("Correo electronico:");

        jtxt_correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_correoActionPerformed(evt);
            }
        });
        jtxt_correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxt_correoKeyReleased(evt);
            }
        });

        jLabel_contraseña.setText("Contraseña:");

        jbtn_cancelar.setText("CANCELAR");
        jbtn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_cancelarActionPerformed(evt);
            }
        });

        jbtn_guardar.setText("GUARDAR");
        jbtn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_guardarActionPerformed(evt);
            }
        });

        jlbl_email.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jlbl_email.setForeground(new java.awt.Color(255, 0, 0));
        jlbl_email.setText("Email invalido(*)");

        jLabel2.setText("Repita Contraseña:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jbtn_guardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtn_cancelar)
                .addGap(102, 102, 102))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jlbl_email))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_nombre)
                            .addComponent(jLabel_correo)
                            .addComponent(jLabel_contraseña)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpass_contraseña)
                            .addComponent(jtxt_correo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxt_nombreUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(jpass_repeatContraseña))))
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nombre)
                    .addComponent(jtxt_nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jlbl_email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_correo))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpass_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_contraseña))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jpass_repeatContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_cancelar)
                    .addComponent(jbtn_guardar))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_cancelarActionPerformed
        FormLogin log = new FormLogin();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbtn_cancelarActionPerformed

    private void jtxt_nombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_nombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_nombreUsuarioActionPerformed

    private void jtxt_correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_correoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_correoActionPerformed

    private void jbtn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_guardarActionPerformed

        String nombreUsuario = this.jtxt_nombreUsuario.getText();
        String correoElectronico = this.jtxt_correo.getText();
        String contrasena = String.valueOf(jpass_contraseña.getPassword());
        String Rcontrasena = String.valueOf(jpass_repeatContraseña.getPassword());
        
        
        if (this.jtxt_nombreUsuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo 'Nombre de usuario' no debe estar vacio", "Registro de usuario", 0); 
            this.jtxt_nombreUsuario.requestFocus();
            return;
        }   
        if (this.jtxt_correo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo 'Correo electronico' no debe estar vacio", "Registro de usuario", 0);
            this.jtxt_correo.requestFocus();
            return;
        }    
        if (!contrasena.equals(Rcontrasena)) {
            JOptionPane.showMessageDialog(null, "Las contraseñas deben ser iguales, vuelva a intentar", "Registro de usuario", 0);          
            System.out.println(contrasena);
            System.out.println(Rcontrasena);
            return;
        }   
        
        Usuario usuario = new Usuario(nombreUsuario, correoElectronico, contrasena);
        RegistroUsuario reg = new RegistroUsuario();
            
        if (reg.AgregarUsuario(usuario)) {
            JOptionPane.showMessageDialog(null, "Registro de usuario exitoso!", "Registro de usuario", 3); 
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "No se pudo completar el registro, vuelva a intentar", "Registro de usuario", 0);
        }
        

    }//GEN-LAST:event_jbtn_guardarActionPerformed

    private void jtxt_correoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_correoKeyReleased
        //EL KEY RELEASED ES PARA IR VERIFICANDO A MEDIDA QUE SE VA ESCRIBIENDO EN EL CAMPO DEL EMAIL
        RegistroUsuario reg = new RegistroUsuario();
        if (reg.verificadorCorreo(jtxt_correo.getText())) {
            jlbl_email.setVisible(false);
        }else{
            jlbl_email.setVisible(true);
        }
    }//GEN-LAST:event_jtxt_correoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_contraseña;
    private javax.swing.JLabel jLabel_correo;
    private javax.swing.JLabel jLabel_nombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtn_cancelar;
    private javax.swing.JButton jbtn_guardar;
    private javax.swing.JLabel jlbl_email;
    private javax.swing.JPasswordField jpass_contraseña;
    private javax.swing.JPasswordField jpass_repeatContraseña;
    private javax.swing.JTextField jtxt_correo;
    private javax.swing.JTextField jtxt_nombreUsuario;
    // End of variables declaration//GEN-END:variables
}
